# Generated by Django 4.1.3 on 2022-12-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miles', models.IntegerField()),
                ('minutes', models.IntegerField()),
            ],
        ),
    ]
