# Generated by Django 4.1.3 on 2022-12-03 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LifeStyleApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='minutes',
            new_name='days',
        ),
    ]
